//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdPicker
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_TempD_BOOKING_LOG
    {
        public int SNO { get; set; }
        public string Booking_ID { get; set; }
        public string Customer_ID { get; set; }
        public Nullable<int> Total_Product { get; set; }
        public Nullable<long> Total_Cost { get; set; }
        public Nullable<System.DateTime> Booking_Time { get; set; }
        public Nullable<int> Delivery_Time { get; set; }
        public string Delivery_Pincode { get; set; }
        public string Delivery_Address { get; set; }
        public string Delivery_Phone { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
