//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdPicker
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_TempD_Product_Weighing_List
    {
        public int SNO { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public string Product_Weighing_ID { get; set; }
        public string Weighing_Type { get; set; }
        public string Weighing_Description { get; set; }
        public Nullable<long> Cost { get; set; }
    }
}
