//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdPicker
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_TempD_Company_Detail
    {
        public int SNO { get; set; }
        public string Company_ID { get; set; }
        public string Company_Name { get; set; }
        public string Company_ImgSrc { get; set; }
    }
}
