//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdPicker
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_TempD_Product_Detail
    {
        public int SNO { get; set; }
        public int Product_ID { get; set; }
        public string Product_Name { get; set; }
        public Nullable<long> Cost { get; set; }
        public Nullable<int> C_Weighing_List { get; set; }
        public string Company_ID { get; set; }
        public string Product_Description { get; set; }
        public string Product_ImgSrc { get; set; }
        public Nullable<int> Availability { get; set; }
        public Nullable<int> Category_ID { get; set; }
    }
}
