//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdPicker
{
    using System;
    using System.Collections.Generic;
    
    public partial class COUGallery
    {
        public int SerialNo { get; set; }
        public string CourseID { get; set; }
        public string GalleryDetail { get; set; }
        public string GalleryURL { get; set; }
    }
}
