//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdPicker
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Edlooker_DevEntities1 : DbContext
    {
        public Edlooker_DevEntities1()
            : base("name=Edlooker_DevEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COUAchievement> COUAchievements { get; set; }
        public virtual DbSet<COUBasicDetail> COUBasicDetails { get; set; }
        public virtual DbSet<COUBatchAvailable> COUBatchAvailables { get; set; }
        public virtual DbSet<COUGallery> COUGalleries { get; set; }
        public virtual DbSet<COULab> COULabs { get; set; }
        public virtual DbSet<COUNew> COUNews { get; set; }
        public virtual DbSet<COURGeneral> COURGenerals { get; set; }
        public virtual DbSet<COUSeminar> COUSeminars { get; set; }
        public virtual DbSet<COUStaffDetail> COUStaffDetails { get; set; }
        public virtual DbSet<COUSubjectList> COUSubjectLists { get; set; }
        public virtual DbSet<COUTestimonial> COUTestimonials { get; set; }
        public virtual DbSet<PCCBriefDetail> PCCBriefDetails { get; set; }
        public virtual DbSet<PCCCompetitorTable> PCCCompetitorTables { get; set; }
        public virtual DbSet<PCCContactDetail> PCCContactDetails { get; set; }
        public virtual DbSet<PCCCourseList> PCCCourseLists { get; set; }
        public virtual DbSet<PCCGallery> PCCGalleries { get; set; }
        public virtual DbSet<PCCGeneralDetail> PCCGeneralDetails { get; set; }
        public virtual DbSet<PCCNew> PCCNews { get; set; }
        public virtual DbSet<PCCSocialMediaDetail> PCCSocialMediaDetails { get; set; }
        public virtual DbSet<PCCTestimonial> PCCTestimonials { get; set; }
        public virtual DbSet<PCCTimelineDetail> PCCTimelineDetails { get; set; }
        public virtual DbSet<PCityDetail> PCityDetails { get; set; }
        public virtual DbSet<PCOLBriefDetail> PCOLBriefDetails { get; set; }
        public virtual DbSet<PCOLCompetitorTable> PCOLCompetitorTables { get; set; }
        public virtual DbSet<PCOLContactDetail> PCOLContactDetails { get; set; }
        public virtual DbSet<PCOLDepartment> PCOLDepartments { get; set; }
        public virtual DbSet<PCOLFaclity> PCOLFaclities { get; set; }
        public virtual DbSet<PCOLGallery> PCOLGalleries { get; set; }
        public virtual DbSet<PCOLGeneralDetail> PCOLGeneralDetails { get; set; }
        public virtual DbSet<PCOLHostel> PCOLHostels { get; set; }
        public virtual DbSet<PCOLNew> PCOLNews { get; set; }
        public virtual DbSet<PCOLReview> PCOLReviews { get; set; }
        public virtual DbSet<PCOLSocialMediaDetail> PCOLSocialMediaDetails { get; set; }
        public virtual DbSet<PCOLSport> PCOLSports { get; set; }
        public virtual DbSet<PCOLTestimonial> PCOLTestimonials { get; set; }
        public virtual DbSet<PCOLTimelineDetail> PCOLTimelineDetails { get; set; }
        public virtual DbSet<PCOLTransport> PCOLTransports { get; set; }
        public virtual DbSet<PCountryDetail> PCountryDetails { get; set; }
        public virtual DbSet<PDEPAchievement> PDEPAchievements { get; set; }
        public virtual DbSet<PDEPBriefDetail> PDEPBriefDetails { get; set; }
        public virtual DbSet<PDEPGallery> PDEPGalleries { get; set; }
        public virtual DbSet<PDEPLab> PDEPLabs { get; set; }
        public virtual DbSet<PDEPLecture> PDEPLectures { get; set; }
        public virtual DbSet<PDEPNew> PDEPNews { get; set; }
        public virtual DbSet<PDEPPlacementCompany> PDEPPlacementCompanies { get; set; }
        public virtual DbSet<PDEPPlacementsBasic> PDEPPlacementsBasics { get; set; }
        public virtual DbSet<PDEPReview> PDEPReviews { get; set; }
        public virtual DbSet<PDEPSeminar> PDEPSeminars { get; set; }
        public virtual DbSet<PDEPStaff> PDEPStaffs { get; set; }
        public virtual DbSet<PDEPSubject> PDEPSubjects { get; set; }
        public virtual DbSet<PDEPTimeline> PDEPTimelines { get; set; }
        public virtual DbSet<PDEPWorkshop> PDEPWorkshops { get; set; }
        public virtual DbSet<PInstitutionRegistration> PInstitutionRegistrations { get; set; }
        public virtual DbSet<PKGCompetitorTable> PKGCompetitorTables { get; set; }
        public virtual DbSet<PKGEventsDetail> PKGEventsDetails { get; set; }
        public virtual DbSet<PKGGallery> PKGGalleries { get; set; }
        public virtual DbSet<PKGTestimonial> PKGTestimonials { get; set; }
        public virtual DbSet<PMessageToInstitution> PMessageToInstitutions { get; set; }
        public virtual DbSet<PSCAchievement> PSCAchievements { get; set; }
        public virtual DbSet<PSCBriefDetail> PSCBriefDetails { get; set; }
        public virtual DbSet<PSCCompetitorTable> PSCCompetitorTables { get; set; }
        public virtual DbSet<PSCContactDetail> PSCContactDetails { get; set; }
        public virtual DbSet<PSCExtraCurricular> PSCExtraCurriculars { get; set; }
        public virtual DbSet<PSCGallery> PSCGalleries { get; set; }
        public virtual DbSet<PSCGeneralDetail> PSCGeneralDetails { get; set; }
        public virtual DbSet<PSCHostel> PSCHostels { get; set; }
        public virtual DbSet<PSCNew> PSCNews { get; set; }
        public virtual DbSet<PSCSocialMediaDetail> PSCSocialMediaDetails { get; set; }
        public virtual DbSet<PSCSport> PSCSports { get; set; }
        public virtual DbSet<PSCTestimonial> PSCTestimonials { get; set; }
        public virtual DbSet<PSCTimelineDetail> PSCTimelineDetails { get; set; }
        public virtual DbSet<PSCTransport> PSCTransports { get; set; }
        public virtual DbSet<PSearchTable> PSearchTables { get; set; }
        public virtual DbSet<PStateDetail> PStateDetails { get; set; }
        public virtual DbSet<PTag> PTags { get; set; }
        public virtual DbSet<PTrendingList> PTrendingLists { get; set; }
        public virtual DbSet<PUserKeyWordSearch> PUserKeyWordSearches { get; set; }
        public virtual DbSet<PUserLocationKeyword> PUserLocationKeywords { get; set; }
        public virtual DbSet<PUserSearch> PUserSearches { get; set; }
        public virtual DbSet<Type> Types { get; set; }
        public virtual DbSet<PKGActivity> PKGActivities { get; set; }
        public virtual DbSet<PKGBriefDetail> PKGBriefDetails { get; set; }
        public virtual DbSet<PKGContactDetail> PKGContactDetails { get; set; }
        public virtual DbSet<PKGDetail> PKGDetails { get; set; }
        public virtual DbSet<PKGSocialMediaDetail> PKGSocialMediaDetails { get; set; }
        public virtual DbSet<PKGTimelineDetail> PKGTimelineDetails { get; set; }
        public virtual DbSet<TestUploadImage> TestUploadImages { get; set; }
        public virtual DbSet<PBLOG> PBLOGs { get; set; }
        public virtual DbSet<PCALENDER> PCALENDERs { get; set; }
        public virtual DbSet<PNEW> PNEWS { get; set; }
        public virtual DbSet<C_TempD_BOOKING_LOG> C_TempD_BOOKING_LOG { get; set; }
        public virtual DbSet<C_TempD_Booking_Product_List> C_TempD_Booking_Product_List { get; set; }
        public virtual DbSet<C_TempD_Category_Detail> C_TempD_Category_Detail { get; set; }
        public virtual DbSet<C_TempD_Company_Detail> C_TempD_Company_Detail { get; set; }
        public virtual DbSet<C_TempD_CUSTOMER_DETAILS> C_TempD_CUSTOMER_DETAILS { get; set; }
        public virtual DbSet<C_TempD_Product_Detail> C_TempD_Product_Detail { get; set; }
        public virtual DbSet<C_TempD_Product_Weighing_List> C_TempD_Product_Weighing_List { get; set; }
    }
}
