//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdPicker
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCCCompetitorTable
    {
        public int SerialNo { get; set; }
        public string InstitutionId { get; set; }
        public string InstitutionIDOne { get; set; }
        public string InstitutionIDTwo { get; set; }
        public string InstitutionIDThree { get; set; }
    }
}
