//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdPicker
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCCCourseList
    {
        public int SerialNo { get; set; }
        public string InstitutionID { get; set; }
        public string Hours { get; set; }
        public string Sessions { get; set; }
        public string Minspersession { get; set; }
        public string Schedule { get; set; }
        public string TotalSeat { get; set; }
        public string CourseURL { get; set; }
        public string CourseName { get; set; }
    }
}
