//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdPicker
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCCGeneralDetail
    {
        public int SerialNos { get; set; }
        public string InstitutionID { get; set; }
        public Nullable<long> NumberofStaff { get; set; }
        public Nullable<long> NumberofStudent { get; set; }
        public Nullable<long> NumberofPlacements { get; set; }
        public Nullable<long> NumberofAssistants { get; set; }
        public Nullable<long> NumberofCourse { get; set; }
        public Nullable<long> NumberofSessions { get; set; }
        public string Parking { get; set; }
        public string AC { get; set; }
    }
}
