//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdPicker
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCOLHostel
    {
        public int SerialNos { get; set; }
        public string InstitutionID { get; set; }
        public string Gender { get; set; }
        public string TotalAvailablity { get; set; }
        public string StudperRoom { get; set; }
        public string AC { get; set; }
        public string Food { get; set; }
        public string Internet { get; set; }
        public string GYM { get; set; }
        public string SwimmingPool { get; set; }
        public string Policestationdistance { get; set; }
        public string Hospitaldistance { get; set; }
    }
}
