//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdPicker
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCOLGeneralDetail
    {
        public int SerialNos { get; set; }
        public string InstitutionID { get; set; }
        public string EnterpreneurshipCell { get; set; }
        public string Scholorship { get; set; }
        public string Canteen { get; set; }
        public string ArtsClub { get; set; }
        public string TechnologyClub { get; set; }
        public string SmartClasses { get; set; }
        public string Transportation { get; set; }
        public string Hostel { get; set; }
        public string RaggingAssociation { get; set; }
        public string NirbhayaAssociation { get; set; }
        public string DepressionAssociation { get; set; }
    }
}
