//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdPicker
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCOLTransport
    {
        public int SerialNos { get; set; }
        public string InstitutionID { get; set; }
        public Nullable<long> TotalBus { get; set; }
        public string Tracking { get; set; }
        public Nullable<long> StudentBus { get; set; }
        public Nullable<long> BusFees { get; set; }
        public string BusRoutes { get; set; }
    }
}
