//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdPicker
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCOLFaclity
    {
        public int SerialNos { get; set; }
        public string InstitutionID { get; set; }
        public Nullable<long> TotalStudents { get; set; }
        public Nullable<long> TotalStaff { get; set; }
        public Nullable<long> TotalDepartments { get; set; }
        public Nullable<long> TotalClubs { get; set; }
        public string Canteen { get; set; }
        public string Transport { get; set; }
        public string Library { get; set; }
    }
}
