//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdPicker
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDEPSubject
    {
        public int SerialNos { get; set; }
        public string DepartmentID { get; set; }
        public string SubjectName { get; set; }
        public Nullable<decimal> Points { get; set; }
    }
}
