//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdPicker
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDEPStaff
    {
        public int SerialNos { get; set; }
        public string DepartmentID { get; set; }
        public Nullable<int> Totalphd { get; set; }
        public Nullable<int> Totaldoctorate { get; set; }
        public Nullable<int> Totalprofessor { get; set; }
        public Nullable<int> Totallabtechnicians { get; set; }
    }
}
