//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdPicker
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDEPAchievement
    {
        public int SerialNos { get; set; }
        public string DepartmentID { get; set; }
        public Nullable<int> Totalprojects { get; set; }
        public Nullable<int> Totalawards { get; set; }
        public Nullable<int> Totalparticipation { get; set; }
        public Nullable<int> Totalpatents { get; set; }
    }
}
