//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdPicker
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDEPReview
    {
        public int SerialNo { get; set; }
        public string DepartmentID { get; set; }
        public string Name { get; set; }
        public string Review { get; set; }
        public string Dated { get; set; }
    }
}
