//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdPicker
{
    using System;
    using System.Collections.Generic;
    
    public partial class PInstitutionRegistration
    {
        public int SNo { get; set; }
        public string InstitutionName { get; set; }
        public string Location { get; set; }
        public string CourseOffered { get; set; }
        public string ContactName { get; set; }
        public string ContactPerson { get; set; }
    }
}
