//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdPicker
{
    using System;
    using System.Collections.Generic;
    
    public partial class PKGActivity
    {
        public int SNO { get; set; }
        public string InstitutionID { get; set; }
        public string OutdoorPlayArea { get; set; }
        public string Painting { get; set; }
        public string Yoga { get; set; }
        public string StoryTelling { get; set; }
        public string StageShow { get; set; }
        public string Learning { get; set; }
        public string Waterpool { get; set; }
        public string Dance { get; set; }
        public string Music { get; set; }
        public string CCTV { get; set; }
    
        public virtual PSearchTable PSearchTable { get; set; }
    }
}
