//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdPicker
{
    using System;
    using System.Collections.Generic;
    
    public partial class PKGDetail
    {
        public int SNO { get; set; }
        public string InstitutionID { get; set; }
        public string TotalStudents { get; set; }
        public string TotalStaff { get; set; }
        public string TotalRooms { get; set; }
        public string Food { get; set; }
        public string Curriculam { get; set; }
        public string Transport { get; set; }
    
        public virtual PSearchTable PSearchTable { get; set; }
    }
}
