//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdPicker
{
    using System;
    using System.Collections.Generic;
    
    public partial class PNEW
    {
        public int SNO { get; set; }
        public string Heading { get; set; }
        public string URL { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> TotalView { get; set; }
        public string Tags { get; set; }
        public string FromSource { get; set; }
        public string ImageSrc { get; set; }
    }
}
