//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdPicker
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSCExtraCurricular
    {
        public int SerialNo { get; set; }
        public string InstitutionID { get; set; }
        public string SmartClassURL { get; set; }
        public string YogaURL { get; set; }
        public string DigitalContentURL { get; set; }
        public string SocialClubURL { get; set; }
        public string StudentTrackingURL { get; set; }
        public string TotalVacationsURL { get; set; }
        public string ArtsClubURL { get; set; }
        public string TechnologyClubURL { get; set; }
        public string WomenSafetyClubURL { get; set; }
        public string LanguageClubURL { get; set; }
    }
}
