//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdPicker
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSCGeneralDetail
    {
        public int SerialNo { get; set; }
        public string InstitutionID { get; set; }
        public Nullable<long> TotalStudents { get; set; }
        public Nullable<long> TotalStaff { get; set; }
        public Nullable<long> TotalSections { get; set; }
        public string Canteen { get; set; }
        public string Curriculam { get; set; }
    }
}
