//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdPicker
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSCHostel
    {
        public int SerialNo { get; set; }
        public string InstitutionID { get; set; }
        public string Gender { get; set; }
        public Nullable<long> TotalAvailablity { get; set; }
        public string HostelCampus { get; set; }
        public Nullable<int> StudentsperRoom { get; set; }
        public string AC { get; set; }
        public string Food { get; set; }
        public string Internet { get; set; }
        public string GYM { get; set; }
        public string SwimmingPool { get; set; }
        public string NearestHospital { get; set; }
        public string NearestPoliceStation { get; set; }
        public string ApproxFees { get; set; }
    }
}
