//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdPicker
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSCSocialMediaDetail
    {
        public int SerialNo { get; set; }
        public string InstitutionID { get; set; }
        public string FacebookAvailableImageURL { get; set; }
        public string FacebookInstitutionURL { get; set; }
        public string InstagramAvailableImageURL { get; set; }
        public string InstagramInstitutionURL { get; set; }
        public string TwitterAvailableImageURL { get; set; }
        public string TwitterInstitutionURL { get; set; }
        public string GoogleplusAvailableImageURL { get; set; }
        public string GoogleplusInstitutionURL { get; set; }
        public string YoutubeAvailableImageURL { get; set; }
        public string YoutubeInstitutionURL { get; set; }
    }
}
