//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdPicker
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSCTimelineDetail
    {
        public int SerialNo { get; set; }
        public string InstitutionID { get; set; }
        public string InstitutionName { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> AdmissionsStatusID { get; set; }
        public Nullable<decimal> InformationRating { get; set; }
        public Nullable<decimal> ReviewRating { get; set; }
        public Nullable<decimal> ReviewPercentage { get; set; }
        public string BoardName { get; set; }
        public string BannerImageURL { get; set; }
        public string ClassRange { get; set; }
    }
}
