//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdPicker
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSearchTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PSearchTable()
        {
            this.PKGActivities = new HashSet<PKGActivity>();
            this.PKGBriefDetails = new HashSet<PKGBriefDetail>();
            this.PKGContactDetails = new HashSet<PKGContactDetail>();
            this.PKGDetails = new HashSet<PKGDetail>();
            this.PKGSocialMediaDetails = new HashSet<PKGSocialMediaDetail>();
            this.PKGTimelineDetails = new HashSet<PKGTimelineDetail>();
        }
    
        public int SerialNo { get; set; }
        public string InstitutionID { get; set; }
        public string InstitutionName { get; set; }
        public string Location { get; set; }
        public string InstitutionImageURL { get; set; }
        public string InstitutionURL { get; set; }
        public string Tags { get; set; }
        public decimal InformationRating { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<bool> PaidStatus { get; set; }
        public Nullable<int> InstitutionType { get; set; }
        public string LocationTags { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<int> ViewCount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PKGActivity> PKGActivities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PKGBriefDetail> PKGBriefDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PKGContactDetail> PKGContactDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PKGDetail> PKGDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PKGSocialMediaDetail> PKGSocialMediaDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PKGTimelineDetail> PKGTimelineDetails { get; set; }
    }
}
